docs/controllers/EffectController.js, docs/controllers/KeyboardController.js, docs/controllers/MouseController.js, docs/controllers/PageController.js, docs/controllers/StageController.js, docs/controllers/stage/Stage01Controller.js, docs/controllers/stage/Stage02Controller.js, docs/index.html, docs/main.js, docs/models/components/Ball.js, docs/models/components/Brick.js, docs/models/components/Paddle.js, docs/models/components/Tool.js, docs/models/effect/BallSizeEffect.js, docs/models/effect/Effect.js, docs/models/effect/PaddleSizeEffect.js, docs/views/SidebarView.js, docs/views/WelcomeView.js
Refactored the effect management and input handling logic in the game to improve modularity and readability. Introduced new controller classes and updated existing components for better separation of concerns.
- Extracted effect-related logic from `StageController` into a separate `EffectController` class.
- Created methods in `EffectController`:
- `applyToolEffect()`: Handles tool effects.
- `activateEffect()`: Activates and manages the duration of effects.
- `removeSameTypeEffect()`: Prevents duplicate effects of the same type.
- `removeActiveEffect()`: Removes expired effects.
- Added `activeEffects` property to track ongoing effects.
- Added `effectController` property for managing effects.
- Delegated all effect-related operations to `effectController`.
- Ensured ball shooting logic …
=> Feat & Refactor:  add pause key and improve ball shooting and update several Controllers

docs/controllers/StageController.js, docs/controllers/stage/Stage03Controller.js, docs/models/effect/TimeEffect.js
Updated so that when timer <= 10, the player loses immediately.
=> added lower limit for TimeEffect (decrease)

docs/controllers/EffectController.js, docs/controllers/StageController.js, docs/controllers/stage/Stage01Controller.js, docs/index.html, docs/models/components/Ball.js, docs/models/components/Tool.js, docs/models/effect/BallInfiniteEffect.js
1. add infinite ball effect
2. add up speed since its too slow
3. add more time for player
=> feat: add infinite ball

docs/controllers/stage/Stage02Controller.js
=> fix: ox -> tiger

docs/controllers/KeyboardController.js
Changed paddle keybinding in 'KeyboardController.js' to arrowUp
=> Changed paddle keybinding to arrowUp

docs/styles/welcome-page.css, docs/views/WelcomeView.js
add game instruction and update version number
=> add game instruction to welcome page

docs/controllers/StageController.js
StageController.js:
- Added this.instructMenuOn in constructor
- Added displayInstructions()
- Updated display()
=> feat: added info window on entry to game stage

docs/controllers/StageController.js
changed pause boolean to true in display() for instructmenuon
=> debugged ops

docs/index.html, docs/views/WelcomeView.js, docs/views/welcome-page/SettingDialog.js
Adjust the setting dialog.
Add a resize method to the setting dialog.
Add a method to close the setting dialog by pressing the C key.
=> Optimize the setting dialog

docs/controllers/PageController.js, docs/controllers/StageController.js, docs/controllers/stage/Stage01Controller.js, docs/controllers/stage/Stage02Controller.js, docs/controllers/stage/Stage03Controller.js, docs/controllers/stage/Stage04Controller.js, docs/controllers/stage/Stage05Controller.js, docs/controllers/stage/Stage06Controller.js, docs/controllers/stage/Stage07Controller.js, docs/controllers/stage/Stage08Controller.js, docs/controllers/stage/Stage09Controller.js, docs/controllers/stage/Stage10Controller.js, docs/controllers/stage/Stage11Controller.js, docs/controllers/stage/Stage12Controller.js, docs/index.html, docs/models/components/Tool.js, docs/models/state/StageState.js, docs/views/ModeView.js, docs/views/StageMapView.js
1. fix: add difficulty mode
2. let different mode has its own toolRate and toolProbabilities
3. fix: prevent from shooting durning pause
4. feat: add ModeView
=> feat: add different mode

docs/controllers/PageController.js, docs/controllers/StageController.js, docs/controllers/stage/Stage01Controller.js, docs/controllers/stage/Stage02Controller.js, docs/controllers/stage/Stage03Controller.js, docs/controllers/stage/Stage04Controller.js, docs/controllers/stage/Stage05Controller.js, docs/controllers/stage/Stage06Controller.js, docs/controllers/stage/Stage07Controller.js, docs/controllers/stage/Stage08Controller.js, docs/controllers/stage/Stage09Controller.js, docs/controllers/stage/Stage10Controller.js, docs/controllers/stage/Stage11Controller.js, docs/controllers/stage/Stage12Controller.js, docs/models/components/StagePattern/Stage05_2.json, docs/views/ModeView.js
1. last pull request I add some selecting mode but there is bug when changing next Stage!
2. also add `showNextFormDialog` when the zodiac sign has second form
3. add blackhole on dragon 2nd
=> fix:select next page bug and feat: add next form Dialog

assignments/Readme.md, assignments/Week09/Readme.md
=> docs: add week09 Homeowork

README.md
Minor tweaks on the text and moved up the heuristic evaluation data (originally the data was in quantitative section)
=> Updated readme qualitative section

docs/controllers/StageController.js
Easy mode info window
Hard mode info window
=> Separated easy and hard level info window + changed C key to ENTER key to start game

assignments/Week08/Readme.md
=> add week8 readme.me

docs/controllers/PageController.js, docs/index.html, docs/views/NewStageMapView.js, docs/views/WelcomeView.js, docs/views/welcome-page/RoadAnimation.js
add new stage map page
Adjust welcome page options
=> add new stage map

docs/views/NewStageMapView.js
=> add a method to return to the menu in the stage map

README.md
Added the challenges in the implementation section
Will need to add in the second draft:
- general description of game (?)
- how challenge 1 (ball speed) was resolved
=> First draft for Docs/implementation

docs/views/GodView.js
Adjusted the keypress event for the God animation
- On the first Enter press, the God animation completes.
- On the second Enter press, it moves to the next dialogue.
- On the third Enter press, the game starts.
=> adjusted the keypress event for the God animation.

docs/index.html, docs/views/PrivacyDialogView.js, docs/views/StageMapView.js
=> added privacy dialog

docs/controllers/KeyboardController.js, docs/controllers/StageController.js, docs/main.js, docs/views/SidebarView.js, docs/views/WelcomeView.js, docs/views/welcome-page/SettingDialog.js
Now the keyboard can be changed in setting
=> Add keyboard changing to setting

README.md
=> add Game Contribution in Conclusion

docs/controllers/StageController.js
=> Change instruction&pause layout

docs/controllers/PageController.js
=> remove useless canvas

docs/controllers/StageController.js, docs/models/effect/BallSpeedEffect.js
The ball's acceleration feature was accidentally deleted last time. This time, it has been added back and the speed has been adjusted.
=> fix: adjust speed
